// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-tJbprZwHh5Oyhm48kE5PVXFnNUdkNso',
    appId: '1:747258885865:web:dd5e62ea848a5af367a278',
    messagingSenderId: '747258885865',
    projectId: 'dishdive-c19d5',
    authDomain: 'dishdive-c19d5.firebaseapp.com',
    storageBucket: 'dishdive-c19d5.appspot.com',
    measurementId: 'G-6HMC8GVV23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATAnxga-641AehWftsZ2v85Scwe5zYU8s',
    appId: '1:747258885865:android:ecc5925a732bda5067a278',
    messagingSenderId: '747258885865',
    projectId: 'dishdive-c19d5',
    storageBucket: 'dishdive-c19d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMYsTjGkNvX6xRDh1oH72vOGZf6oiz3vk',
    appId: '1:747258885865:ios:bddffee53eeee08a67a278',
    messagingSenderId: '747258885865',
    projectId: 'dishdive-c19d5',
    storageBucket: 'dishdive-c19d5.appspot.com',
    iosClientId: '747258885865-sr5bng24sbocmgor446n41oqun3uoic6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dishDive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMYsTjGkNvX6xRDh1oH72vOGZf6oiz3vk',
    appId: '1:747258885865:ios:2de8c3e2169d5dc167a278',
    messagingSenderId: '747258885865',
    projectId: 'dishdive-c19d5',
    storageBucket: 'dishdive-c19d5.appspot.com',
    iosClientId: '747258885865-820amn9kbkjco5i7qtb28mm43tfdt4k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dishDive.RunnerTests',
  );
}
